### ISSUE TITLE
pypi version not usable

### ISSUE THREAD

**Issue by hyhuang00** [willtownes/glmpca-py#14]
The pypi version of glmpca is not usable. The module is empty (no member functions can be found by entering `dir(glmpca)`). This problem is usually caused by error in the `__init__.py` file.

**Comment by willtownes** [comment]
I was able to reproduce this. Thanks for letting me know! Will work on fixing it asap.

**Comment by willtownes** [comment]
Sorry this took so long. This is probably a usability issue resulting from my misunderstanding the python packaging conventions. So the way you can get it to work is 
```from glmpca import glmpca```
which will provide glmpca as a module and it has the glmpca function under it. Alternatively you should be able to do 
```from glmpca.glmpca import glmpca```
to load only the glmpca function (not the module). I realize this is confusing. Do you have any suggestions about how I could reorganize the package so people can just use 
```import glmpca```
instead?

**Comment by willtownes** [comment]
note to self- probably need to put an import statement of the glmpca module in the __init__.py file
