### ISSUE TITLE
Do you feed this raw data or the covariance matrix?

### ISSUE THREAD

**Issue by AngCamp** [willtownes/glmpca-py#17]
This seems really interesting just wondering if you feed this algorithm your data raw or with the covariance matrix?  I'm planning on fitting a Poisson model to some time-series data I have.

**Comment by willtownes** [comment]
Hi, thanks for your interest. I regret to say I have not been able to maintain this code base over the years so it might not work very well. You are welcome to try it though. It is supposed to work on raw count data. You might want to check out some other (faster) approaches too such as [Pearson residuals](https://github.com/berenslab/umi-normalization) and [FastRNA](https://github.com/hanbin973/FastRNA).

**Comment by AngCamp** [comment]
I can always make a python environment for it.  Do you happen to have a .yml lying around that would be useful?

I was actually planning on running this on spiking data from neurons (neuropixels probes) and fit it to the Poisson distribution.  Each time point would be a sample, sampling rate is 1250 Hz with an hour or more per recording.  So the algorithms run time may be an issue, but I can always bin the spikes to deal with overly sparse and large input.  I do have rather powerful computers to run it on though.  256GB Ram and 24+ cores.

**Comment by willtownes** [comment]
Oh, for that check out the work from Jonathan Pillow's group. This [review article](https://doi.org/10.1016/j.conb.2020.11.005) is a good starting point. I think they have python implementations of most of their methods, you could email them if they aren't easily findable on the web.

And sorry no I don't have a YML file.
